#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada
n1 = int(input('Digite um número para ver sua tabuada:'))
print('-'*12)
print('{:4}x{}={}'.format(n1, 1, n1*1))
print('{:4}x{}={}'.format(n1, 2, n1*2))
print('{:4}x{}={}'.format(n1, 3, n1*3))
print('{:4}x{}={}'.format(n1, 4, n1*4))
print('{:4}x{}={}'.format(n1, 5, n1*5))
print('{:4}x{}={}'.format(n1, 6, n1*6))
print('{:4}x{}={}'.format(n1, 7, n1*7))
print('{:4}x{}={}'.format(n1, 8, n1*8))
print('{:4}x{}={}'.format(n1, 9, n1*9))
print('{:4}x{}={}'.format(n1, 10, n1*10))
print('-' * 12)
